name = "MonteCarloMeasurements"
uuid = "0987c9cc-fe09-11e8-30f0-b96dd679fdca"
authors = ["baggepinnen <baggepinnen@gmail.com>"]
version = "0.9.10"

[deps]
CuArrays = "3a865a2d-5b23-5a0f-bc46-62713ec82fae"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
GenericLinearAlgebra = "14197337-ba66-59df-a3e3-ca00e7dcff7a"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
SLEEFPirates = "476501e8-09a2-5ece-8869-fb82de89a1fa"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Distributions = "0.17,0.18,0.19,0.20,0.21, 0.22, 0.23, 0.24"
GenericLinearAlgebra = "<0.3"
MacroTools = "<0.6"
RecipesBase = "<0.8, 0.8, 1.0"
Requires = "<0.6, 1.0"
SLEEFPirates = "0.4, 0.5"
StaticArrays = "<0.12, 0.12"
StatsBase = "0.29, 0.30, 0.32, 0.33"
julia = "1.0"

[extras]
ControlSystems = "a6e380b2-a6ca-5380-bf3e-84a91bcd477e"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Measurements = "eff96d63-e80a-5855-80a2-b1b0885c5ab7"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[targets]
test = ["ControlSystems", "ForwardDiff", "Measurements", "Test", "Plots", "Unitful"]
